// Generated by Wrangler on Sat Jun 01 2024 15:35:20 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	BOT_TOKEN: string;
	API_SECRET: string;
	POWERON_TOKEN: string;
}
