// Generated by Wrangler on Wed May 01 2024 02:31:38 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	BOT_TOKEN: string;
	API_SECRET: string;
	POWERON_TOKEN: string;
	API_BASE: string;
}
