import React from 'react';

export default () => <div className="relative bg-repeat-x h-150px" style={{ marginTop: 50, backgroundImage: 'url(/img/bg_pc.avif)', backgroundSize: '700px 155px' }}>
	<div style={{ textAlign: 'center', color: 'white', fontSize: 18 }} className="absolute bottom-7px w-full">
		Rating on AquaDX.Net | Designed by Clansty feat. 7Yunluo | Generated by @AquaDXBot | Data from DXRating.net
	</div>
</div>
