// Generated by Wrangler on Sat May 18 2024 03:30:01 GMT+0800 (China Standard Time)
// by running `wrangler types`

import { BrowserWorker } from '@cloudflare/puppeteer';

interface Env {
	KV: KVNamespace;
	BOT_TOKEN: string;
	API_SECRET: string;
	POWERON_TOKEN: string;
	API_BASE: string;
	MYBROWSER: BrowserWorker;
}
